/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Exception.PersistenciaException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author icoro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        setTitle("Agencia Fiscal");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JDesktopPane();
        menuPrincipal = new javax.swing.JMenuBar();
        menuTarmites = new javax.swing.JMenu();
        itemLicencias = new javax.swing.JMenuItem();
        itemPlacas = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        itemHistorial = new javax.swing.JMenuItem();
        itemBusquedaRFC = new javax.swing.JMenuItem();
        itemBusquedaNombre = new javax.swing.JMenuItem();
        itemBusquedaNacimiento = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemReportes = new javax.swing.JMenuItem();
        menuArchivo = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        menuTarmites.setText("Tramites");

        itemLicencias.setText("Licencias");
        itemLicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLicenciasActionPerformed(evt);
            }
        });
        menuTarmites.add(itemLicencias);

        itemPlacas.setText("Placas");
        itemPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPlacasActionPerformed(evt);
            }
        });
        menuTarmites.add(itemPlacas);

        menuPrincipal.add(menuTarmites);

        menuConsultas.setText("Consultas");

        itemHistorial.setText("Historial por persona");
        itemHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHistorialActionPerformed(evt);
            }
        });
        menuConsultas.add(itemHistorial);

        itemBusquedaRFC.setText("Buscar por RFC");
        itemBusquedaRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBusquedaRFCActionPerformed(evt);
            }
        });
        menuConsultas.add(itemBusquedaRFC);

        itemBusquedaNombre.setText("Buscar por nombre");
        itemBusquedaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBusquedaNombreActionPerformed(evt);
            }
        });
        menuConsultas.add(itemBusquedaNombre);

        itemBusquedaNacimiento.setText("Buscar por año de nacimiento");
        itemBusquedaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBusquedaNacimientoActionPerformed(evt);
            }
        });
        menuConsultas.add(itemBusquedaNacimiento);

        menuPrincipal.add(menuConsultas);

        menuReportes.setText("Reportes");

        itemReportes.setText("Reporte de tramites realizados");
        itemReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReportesActionPerformed(evt);
            }
        });
        menuReportes.add(itemReportes);

        menuPrincipal.add(menuReportes);

        menuArchivo.setText("Salir");

        itemSalir.setText("Salir del programa");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(itemSalir);

        menuPrincipal.add(menuArchivo);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemLicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLicenciasActionPerformed
        panelCentral.removeAll();
        FILicencias lic = null;
        try {
            lic = new FILicencias();
        } catch (PersistenciaException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelCentral.add(lic);
        try { lic.setSelected(true); } catch (java.beans.PropertyVetoException e) {}
        panelCentral.revalidate();
        panelCentral.repaint();
    }//GEN-LAST:event_itemLicenciasActionPerformed

    private void itemHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHistorialActionPerformed
       panelCentral.removeAll();
        FIHistorial historial = null;
        try {
            historial = new FIHistorial();
        } catch (PersistenciaException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelCentral.add(historial);
        try { historial.setSelected(true); } catch (java.beans.PropertyVetoException e) {}
        panelCentral.revalidate();
        panelCentral.repaint();
    }//GEN-LAST:event_itemHistorialActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
       Object[] opciones = {"Sí", "No"};
int resp = JOptionPane.showOptionDialog(
        this,
        "¿Deseas salir?",
        "Salir",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        opciones,
        opciones[1] 
);

if(resp == 0){ 
    System.exit(0);
}



    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPlacasActionPerformed
       panelCentral.removeAll();
        FIPlacas placas = null;
        try {
            placas = new FIPlacas();
        } catch (PersistenciaException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelCentral.add(placas);
        try { placas.setSelected(true); } catch (java.beans.PropertyVetoException e) {}
        panelCentral.revalidate();
        panelCentral.repaint();
    }//GEN-LAST:event_itemPlacasActionPerformed

    private void itemBusquedaRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBusquedaRFCActionPerformed
       panelCentral.removeAll();
        FIRfc rfcs = new FIRfc();
        panelCentral.add(rfcs);
        try { rfcs.setSelected(true); } catch (java.beans.PropertyVetoException e) {}
        panelCentral.revalidate();
        panelCentral.repaint();
    }//GEN-LAST:event_itemBusquedaRFCActionPerformed

    private void itemBusquedaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBusquedaNombreActionPerformed
        panelCentral.removeAll();
        FINombre nombres = new FINombre();
        panelCentral.add(nombres);
        try { nombres.setSelected(true); } catch (java.beans.PropertyVetoException e) {}
        panelCentral.revalidate();
        panelCentral.repaint();
    }//GEN-LAST:event_itemBusquedaNombreActionPerformed

    private void itemBusquedaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBusquedaNacimientoActionPerformed
       panelCentral.removeAll();
        FINacimiento nacimiento = new FINacimiento();
        panelCentral.add(nacimiento);
        try { nacimiento.setSelected(true); } catch (java.beans.PropertyVetoException e) {}
        panelCentral.revalidate();
        panelCentral.repaint();
    }//GEN-LAST:event_itemBusquedaNacimientoActionPerformed

    private void itemReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReportesActionPerformed
        panelCentral.removeAll();
        FIReportes reportes = null;
        try {
            reportes = new FIReportes();
        } catch (PersistenciaException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelCentral.add(reportes);
        try { reportes.setSelected(true); } catch (java.beans.PropertyVetoException e) {}
        panelCentral.revalidate();
        panelCentral.repaint();
    }//GEN-LAST:event_itemReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemBusquedaNacimiento;
    private javax.swing.JMenuItem itemBusquedaNombre;
    private javax.swing.JMenuItem itemBusquedaRFC;
    private javax.swing.JMenuItem itemHistorial;
    private javax.swing.JMenuItem itemLicencias;
    private javax.swing.JMenuItem itemPlacas;
    private javax.swing.JMenuItem itemReportes;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuTarmites;
    private javax.swing.JDesktopPane panelCentral;
    // End of variables declaration//GEN-END:variables
}
